name: ento_any
description: "A Flutter package that provides a simple transliterator with language selection capabilities, enabling users to convert text easily with suggestions from an API."
version: 0.0.1
homepage: https://github.com/kashyapsandesh/ento_any
environment:
  sdk: ">=3.3.3 <4.0.0"
  flutter: ">=1.17.0"

dependencies:
  flutter:
    sdk: flutter
  http: ^1.2.2

dev_dependencies:
  flutter_lints: ^3.0.0
  flutter_test:
    sdk: flutter
